window.DEFAULT_MATERIALS = [
  {
    "code": "CF01",
    "group": "Cà phê",
    "name": "Cà phê Mộc Nguyên",
    "stockUnit": "kg",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 0,
    "minStock": 2000,
    "active": true
  },
  {
    "code": "CF02",
    "group": "Cà phê",
    "name": "Cafe Basic 3",
    "stockUnit": "kg",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 0,
    "minStock": 2000,
    "active": true
  },
  {
    "code": "CF03",
    "group": "Cà phê",
    "name": "Hạt Blend",
    "stockUnit": "kg",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 0,
    "minStock": 2000,
    "active": true
  },
  {
    "code": "CF04",
    "group": "Cà phê",
    "name": "Hạt Arab",
    "stockUnit": "kg",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 0,
    "minStock": 1500,
    "active": true
  },
  {
    "code": "SU01",
    "group": "Sữa",
    "name": "Sữa tươi Đà Lạt Milk",
    "stockUnit": "hộp",
    "baseUnit": "ml",
    "packSize": 1000,
    "tareWeight": 35,
    "minStock": 6000,
    "active": true
  },
  {
    "code": "SU02",
    "group": "Sữa",
    "name": "Sữa đặc Star",
    "stockUnit": "lon",
    "baseUnit": "g",
    "packSize": 1284,
    "tareWeight": 150,
    "minStock": 2500,
    "active": true
  },
  {
    "code": "SU03",
    "group": "Sữa",
    "name": "Sữa chua",
    "stockUnit": "hộp",
    "baseUnit": "g",
    "packSize": 100,
    "tareWeight": 12,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "SU04",
    "group": "Sữa",
    "name": "Rich lùn",
    "stockUnit": "hộp",
    "baseUnit": "ml",
    "packSize": 907,
    "tareWeight": 55,
    "minStock": 1800,
    "active": true
  },
  {
    "code": "SU05",
    "group": "Sữa",
    "name": "Sữa Oatside",
    "stockUnit": "hộp",
    "baseUnit": "ml",
    "packSize": 1000,
    "tareWeight": 38,
    "minStock": 3000,
    "active": true
  },
  {
    "code": "MU01",
    "group": "Mứt",
    "name": "Sốt dâu Boduo",
    "stockUnit": "hũ",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 120,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "MU02",
    "group": "Mứt",
    "name": "Sốt xoài Boduo",
    "stockUnit": "hũ",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 120,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "MU03",
    "group": "Mứt",
    "name": "Mứt ổi Boduo",
    "stockUnit": "hũ",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 120,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "MU04",
    "group": "Mứt",
    "name": "Mứt vải Boduo",
    "stockUnit": "hũ",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 120,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "MU05",
    "group": "Mứt",
    "name": "Mứt việt quất Osterberg",
    "stockUnit": "chai",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 110,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "MU06",
    "group": "Mứt",
    "name": "Hibiscus Onefood",
    "stockUnit": "hũ",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 120,
    "minStock": 800,
    "active": true
  },
  {
    "code": "SY01",
    "group": "Syrup",
    "name": "Syrup Torani",
    "stockUnit": "chai",
    "baseUnit": "ml",
    "packSize": 750,
    "tareWeight": 320,
    "minStock": 1500,
    "active": true
  },
  {
    "code": "SY02",
    "group": "Syrup",
    "name": "Syrup Hershey's Chocolate",
    "stockUnit": "chai",
    "baseUnit": "ml",
    "packSize": 680,
    "tareWeight": 280,
    "minStock": 1360,
    "active": true
  },
  {
    "code": "LO01",
    "group": "Lon/Hộp",
    "name": "Đào lon Boduo",
    "stockUnit": "lon",
    "baseUnit": "g",
    "packSize": 820,
    "tareWeight": 120,
    "minStock": 1640,
    "active": true
  },
  {
    "code": "LO02",
    "group": "Lon/Hộp",
    "name": "Vải thiều lon Ngọc Hà",
    "stockUnit": "lon",
    "baseUnit": "g",
    "packSize": 565,
    "tareWeight": 105,
    "minStock": 1130,
    "active": true
  },
  {
    "code": "LO03",
    "group": "Lon/Hộp",
    "name": "Cốt dừa Wonderfarm",
    "stockUnit": "lon",
    "baseUnit": "ml",
    "packSize": 400,
    "tareWeight": 90,
    "minStock": 800,
    "active": true
  },
  {
    "code": "LO04",
    "group": "Lon/Hộp",
    "name": "Soda",
    "stockUnit": "chai",
    "baseUnit": "ml",
    "packSize": 330,
    "tareWeight": 25,
    "minStock": 1980,
    "active": true
  },
  {
    "code": "LO05",
    "group": "Lon/Hộp",
    "name": "Chanh muối Thanh Bình",
    "stockUnit": "hũ",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 150,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "TR01",
    "group": "Trà",
    "name": "Trà đào Cozy",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "TR02",
    "group": "Trà",
    "name": "Trà quế AHMAD",
    "stockUnit": "hộp",
    "baseUnit": "g",
    "packSize": 400,
    "tareWeight": 35,
    "minStock": 800,
    "active": true
  },
  {
    "code": "TR03",
    "group": "Trà",
    "name": "Trà Loving Savo",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "TR04",
    "group": "Trà",
    "name": "Trà gừng Hotginger",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 800,
    "active": true
  },
  {
    "code": "TR05",
    "group": "Trà",
    "name": "Trà Olong nướng Hi Tea 500g",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "TR06",
    "group": "Trà",
    "name": "Trà Olong Trúc Hi Tea",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "TR07",
    "group": "Trà",
    "name": "Trà lài Vinsaf",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "TR08",
    "group": "Trà",
    "name": "Trà sâm dứa Bảo Ngân 350g",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 350,
    "tareWeight": 7,
    "minStock": 700,
    "active": true
  },
  {
    "code": "BO01",
    "group": "Bột",
    "name": "Bột sữa Gourmet 1kg",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 15,
    "minStock": 2000,
    "active": true
  },
  {
    "code": "BO02",
    "group": "Bột",
    "name": "Bột Frappe",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 15,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "BO03",
    "group": "Bột",
    "name": "Bột Chocolate Grand-place",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 15,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "BO04",
    "group": "Bột",
    "name": "Bột Matcha Powder Taiwan",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 10,
    "minStock": 500,
    "active": true
  },
  {
    "code": "BO05",
    "group": "Bột",
    "name": "Bột Matcha Natsu",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 10,
    "minStock": 500,
    "active": true
  },
  {
    "code": "BO06",
    "group": "Bột",
    "name": "Bột Matcha Haru",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 10,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH01",
    "group": "Khác",
    "name": "Sương sáo",
    "stockUnit": "hộp",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 100,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "KH02",
    "group": "Khác",
    "name": "Trân châu 3Q",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 2000,
    "tareWeight": 20,
    "minStock": 2000,
    "active": true
  },
  {
    "code": "KH03",
    "group": "Khác",
    "name": "Mật ong Tam Đảo",
    "stockUnit": "chai",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 180,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "KH04",
    "group": "Khác",
    "name": "Muối hồng Himalaya",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH05",
    "group": "Khác",
    "name": "Ngũ cốc Pete",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH06",
    "group": "Khác",
    "name": "Nha đam Xuân Thịnh",
    "stockUnit": "hộp",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 100,
    "minStock": 1000,
    "active": true
  },
  {
    "code": "KH07",
    "group": "Khác",
    "name": "Xí muội",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH08",
    "group": "Khác",
    "name": "Muối xí muội",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH09",
    "group": "Khác",
    "name": "Đường cát trắng",
    "stockUnit": "kg",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 0,
    "minStock": 5000,
    "active": true
  },
  {
    "code": "KH10",
    "group": "Khác",
    "name": "Đường đen Hàn Quốc",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 1000,
    "tareWeight": 15,
    "minStock": 2000,
    "active": true
  },
  {
    "code": "KH11",
    "group": "Khác",
    "name": "Cam khô",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH12",
    "group": "Khác",
    "name": "Hoa đậu biếc",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 200,
    "tareWeight": 5,
    "minStock": 200,
    "active": true
  },
  {
    "code": "KH13",
    "group": "Khác",
    "name": "Hoa lài",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 200,
    "tareWeight": 5,
    "minStock": 200,
    "active": true
  },
  {
    "code": "KH14",
    "group": "Khác",
    "name": "Hoa hồng",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 200,
    "tareWeight": 5,
    "minStock": 200,
    "active": true
  },
  {
    "code": "KH15",
    "group": "Khác",
    "name": "Quế khô",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH16",
    "group": "Khác",
    "name": "Bánh Oreo",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 300,
    "tareWeight": 10,
    "minStock": 600,
    "active": true
  },
  {
    "code": "KH17",
    "group": "Khác",
    "name": "Vụn dừa nướng",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH18",
    "group": "Khác",
    "name": "Cam thảo",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH19",
    "group": "Khác",
    "name": "Kỷ tử",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH20",
    "group": "Khác",
    "name": "Táo đỏ",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH21",
    "group": "Khác",
    "name": "Hạt dưa",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH22",
    "group": "Khác",
    "name": "Hạt hướng dương",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH23",
    "group": "Khác",
    "name": "Đậu phộng",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  },
  {
    "code": "KH24",
    "group": "Khác",
    "name": "Hạt chia",
    "stockUnit": "gói",
    "baseUnit": "g",
    "packSize": 500,
    "tareWeight": 8,
    "minStock": 500,
    "active": true
  }
];
